### ISSUE TITLE
인프런 개인 강의 2개, 재형 추천 강의 총 3개

### ISSUE THREAD

**Issue by doyou1** [Chukapoka/server#2]

**Comment by sin-hyunjin** [comment]
> ### [스프링 부트, 웹 MVC, DB 접근 기술](https://www.inflearn.com/course/%EC%8A%A4%ED%94%84%EB%A7%81-%EC%9E%85%EB%AC%B8-%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8/dashboard)
> * [Repository 정리](https://github.com/sin-hyunjin/spring-learning/tree/main/spring-webmvc-db)
> * 진행 사항 84%
> 
> ### [스프링부트 시큐리티 & JWT 강의](https://www.inflearn.com/course/%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8-%EC%8B%9C%ED%81%90%EB%A6%AC%ED%8B%B0)
> ### [스프링부트 기본편](https://www.inflearn.com/course/%EC%8A%A4%ED%94%84%EB%A7%81-%ED%95%B5%EC%8B%AC-%EC%9B%90%EB%A6%AC-%EA%B8%B0%EB%B3%B8%ED%8E%B8)

**Comment by doyou1** [comment]
1/4
- 다음거는 내일 저녁 1/5까지 들을 예정

**Comment by sin-hyunjin** [comment]
### [스프링 부트, 웹 MVC, DB 접근 기술](https://www.inflearn.com/course/%EC%8A%A4%ED%94%84%EB%A7%81-%EC%9E%85%EB%AC%B8-%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8/dashboard)
[Repository 정리](https://github.com/sin-hyunjin/spring-learning/tree/main/spring-webmvc-db)
진행 사항 84%

### [vue3+spring+mariaDB로 회원 관리 구현](https://www.youtube.com/watch?v=povDCmh3BfM&list=PLfpRlCqycThkmL-HIcAf542NefEZtQFrV&index=1&ab_channel=%EC%89%98%ED%8F%B4%EB%8D%94ShellFolder)

- [Repository 정리](https://github.com/sin-hyunjin/spring-learning/tree/main/vue3-springBoot)
- 진행사항 100% 
- jwt강의 듣다가 vue3도 알겸 들어봄
- api설계서 보면서 로직구현할수있을듯

### [스프링부트 시큐리티 & JWT 강의](https://www.inflearn.com/course/%EC%8A%A4%ED%94%84%EB%A7%81%EB%B6%80%ED%8A%B8-%EC%8B%9C%ED%81%90%EB%A6%AC%ED%8B%B0)

### [스프링부트 기본편](https://www.inflearn.com/course/%EC%8A%A4%ED%94%84%EB%A7%81-%ED%95%B5%EC%8B%AC-%EC%9B%90%EB%A6%AC-%EA%B8%B0%EB%B3%B8%ED%8E%B8)
