### ISSUE TITLE
스프링 시큐리티, jwt 강의 & api 설계서 작성

### ISSUE THREAD

**Issue by doyou1** [Chukapoka/server#7]

**Comment by doyou1** [comment]
1. https://www.inflearn.com/course/%EC%BD%94%ED%8B%80%EB%A6%B0%EA%B3%BC-spring-security-jwt-%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85%EB%A7%8C%EB%93%A4%EA%B8%B0/dashboard
   - 강의듣기
2. 설명해준 방식대로 api 설계 내용 보고 `yml` 파일로 설계서 작성

01/08까지

**Comment by sin-hyunjin** [comment]
## [kotlin-spring-security](https://github.com/sin-hyunjin/spring-learning/blob/main/kotlin-spring-security)
- 강의 [레포지토리 작성](https://github.com/sin-hyunjin/spring-learning/tree/main/kotlin-spring-security)
- api 설계서 작성 (수정필요)
https://beneficial-beetle-699.notion.site/API-V1-e84e7f0835e04b949c8f6a2f50686fda

**Comment by doyou1** [comment]
### 전체적으로 깔끔쓰! 실제 작업 들어가면서 바뀌겠지만,,,, 일단 아래 사항만 수정하면, 바로 개발 들어갈 수 있을 듯!!
 
- `DEL /api/tree/${treeId}`로 변경
    - 트리삭제 엔드포인트를`/api/treeDel/${treeId}`로 하는건 restful 하지않음. 엔드포인트는 동일하나 method(`GET`, `POST`, `DELETE`) 등으로 하는 역할을 유추 및 정의할 수 있게 해야함 
- `GET /api/tree?id={id}` -> `GET /api/tree`로 변경
    - 토큰에 담겨있는 userId를 추출해서 서버단에서 가져오는 걸로하자(userId를 GET의 query 방식으로 보내는건 위험해 보임)
- `GET /api/treeItem?id={id}` -> `GET /api/treeItem`로 변경
    - 위와 동일한 이유

![Image](https://github.com/Chukapoka/server/assets/56281493/f682abc5-115a-4194-bb88-25b5f160f771)
- 같은 에러 뜨는지는 모르겠는데, 에러 뜨는 부분 있으면 수정 부탁

**Comment by sin-hyunjin** [comment]
![Image](https://github.com/Chukapoka/server/assets/116487398/99f58c18-c860-4a51-854e-d45282b48d2a)

  - [API설계서 수정](https://www.notion.so/API-V1-e84e7f0835e04b949c8f6a2f50686fda)


- 위에 내용에 따라 전체적으로 수정하였음
- email이나 id로 쿼리 매개변수로 받았을 때의 문법오류가 있어서 
 ```
parameters:
        - name: id
          in: query
          description: 사용자 이메일 또는 아이디
          required: true
          schema:
            type: string
```
prameters 안에서 쿼리로 지정함
