### ISSUE TITLE
vue - spring boot - postgresql 회원가입, 로그인 샘플링

### ISSUE THREAD

**Issue by doyou1** [Chukapoka/server#9]

**Comment by sin-hyunjin** [comment]
-[/api/user/** API 관련한 로직구현](https://github.com/Chukapoka/server/commit/6f50ed1ce72d7359b775716158f79bf5a0172109)

- 로그인 또는 회원가입이 비밀번호 토큰처리 필요함 (Security, JWT 사용해야함)
     -  SecurityConfig 관련 6.1 버전이상부터는 람다식을 통해 함수형으로 설정하게함
- 회원이 아닐시 이메일 인증번호 보내는 라이브러리 찾고 로직 구현해야함
[참고해 볼만한 블로그](https://velog.io/@dionisos198/%EC%8A%A4%ED%94%84%EB%A7%81%EC%9C%BC%EB%A1%9C-%EC%9D%B4%EB%A9%94%EC%9D%BC-%EC%9D%B8%EC%A6%9D-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0)

**Comment by doyou1** [comment]
@seungyeonnn @Jung-eunwoo 
백엔드 개발 완료되면, api 연동? 코드 설명드릴게요(vue-query)

**Comment by doyou1** [comment]
https://github.com/Chukapoka/client/pull/17
